Feature/gallery
pavel-sheremet-dev/goit-tp-1 pull request #23
Opened 2021-07-18 19:09 UTC by Yevhenii-bs

Закончил секцию галерея, проверьте, пож-та (особенно что касается отрицательных маржинов).
В секции _"Advantages"_:
   - добавил половину расстояния в качестве верхнего паддинга.
Также, **просьба автору** секции _"Customer reviews"_:
   - добавить в верхний паддинг равный полностью всему расстоянию между элементами с макета (т.к. если я ставлю половину этого расстояния, мои нижние сбиваются из-за отрицательных маржинов).

2021-07-18 19:58 UTC, pavel-sheremet-dev requested changes
Поправишь на досуге

2021-07-18 19:58 UTC, pavel-sheremet-dev commented on src/partials/gallery.html
> -<section class="gallery">
class="gallery"

2021-07-18 19:58 UTC, pavel-sheremet-dev commented on src/partials/gallery.html
> +    <div class="container gallery">
gallery поменять на gallery__container

2021-07-18 19:58 UTC, pavel-sheremet-dev commented on src/sass/layout/_gallery.scss
> +.gallery {
.gallery__container

2021-07-18 19:58 UTC, pavel-sheremet-dev commented on src/sass/layout/_gallery.scss
> +  .gallery {
.gallery__container

2021-07-18 19:58 UTC, pavel-sheremet-dev commented on src/sass/layout/_gallery.scss
> +  .gallery {
.gallery__container

2021-07-18 19:58 UTC, pavel-sheremet-dev commented on src/sass/layout/_gallery.scss
> +
.gallery {
padding-bottom: 40px;
}

2021-07-18 19:58 UTC, pavel-sheremet-dev commented on src/sass/layout/_gallery.scss
> +@media screen and (min-width: $desktop) {
.gallery {
padding-bottom: 60px
}

2021-07-19 06:39 UTC, Yevhenii-bs commented on src/partials/gallery.html
> +    <div class="container gallery">
+

2021-07-19 06:41 UTC, Yevhenii-bs commented on src/partials/gallery.html
> -<section class="gallery">
+

2021-07-19 08:54 UTC, pavel-sheremet-dev requested changes
В телеграме.

2021-07-19 08:54 UTC, pavel-sheremet-dev commented on src/sass/layout/_gallery.scss
> +  padding-bottom: 45px;
40px

2021-07-19 08:54 UTC, pavel-sheremet-dev commented on src/sass/layout/_gallery.scss
> +  padding-bottom: 45px;
ПО макету общий отступ 80px на две секции

2021-07-19 08:59 UTC, Yevhenii-bs commented on src/sass/layout/_gallery.scss
> +  padding-bottom: 45px;
done

2021-07-19 09:20 UTC, pavel-sheremet-dev approved these changes

2021-07-19 09:20 UTC, merged